name: Deploy to Render
run-name: Deploying backend to Render

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/render-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/download/v2.1.4/cli_2.1.4_linux_amd64.zip -o render.zip
          unzip render.zip
          sudo mv cli_v2.1.4 /usr/local/bin/render
          render --version
      
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          # Deploy and wait for completion
          render deploys create ${{ secrets.RENDER_SERVICE_ID }} \
            --output json \
            --confirm \
            --wait \
            --commit ${{ github.sha }}
      
      - name: Check deployment status
        if: success()
        run: echo "✅ Deployment successful!"
      
      - name: Notify on failure
        if: failure()
        run: echo "❌ Deployment failed! Check Render logs."