# This is a simple GitHub Actions example for learning

name: My First Workflow

# When should this run?
on:
  push:                      # Run when code is pushed
    branches: [ master ]     # Only on master branch

# What should it do?
jobs:
  say-hello:                 # Job name (you choose)
    runs-on: ubuntu-latest   # Use Ubuntu Linux
    
    steps:
    # Step 1: Get the code
    - name: Download code
      uses: actions/checkout@v4
    
    # Step 2: Say hello
    - name: Say hello
      run: echo "Hello from GitHub Actions!"
    
    # Step 3: Show current directory
    - name: Show files
      run: |
        echo "Current directory:"
        ls -la
    
    # Step 4: Show date
    - name: What time is it?
      run: date